version: "3.8"

services:
  be:
    build: .
    container_name: order_management_be
    ports:
      - "5001:3000"
    env_file:
      - .env
    networks:
      - shared_pg_network
      # - order_net
    restart: unless-stopped

networks:
  shared_pg_network:
    external: true
